/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2024-07-21 08:53:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Welcome2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/DUP-REP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ROOT/WEB-INF/lib/struts2-core-2.5.10.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1488779942000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.10.1.jar", Long.valueOf(1721541534948L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fa_0026_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fa_0026_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.release();
    _005fjspx_005ftagPool_005fs_005fa_0026_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write(" span {\r\n");
      out.write("background-color: #008cba;\r\n");
      out.write("border-color: #007095;\r\n");
      out.write("color: white;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("cursor: default;\r\n");
      out.write("opacity: 0.7;\r\n");
      out.write("box-shadow: none;\r\n");
      out.write("padding: 5px 5px 5px 5px;\r\n");
      out.write(" border: 1px solid  #007095;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("#table-wrapper {\r\n");
      out.write("  position:relative;\r\n");
      out.write("}\r\n");
      out.write("#table-scroll {\r\n");
      out.write("  height:500px;\r\n");
      out.write("  overflow:auto;  \r\n");
      out.write("  margin-top:20px;\r\n");
      out.write("}\r\n");
      out.write("#table-wrapper table {\r\n");
      out.write("  width:100%;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("#table-wrapper table thead th .text {\r\n");
      out.write("  position:absolute;   \r\n");
      out.write("  top:-20px;\r\n");
      out.write("  z-index:2;\r\n");
      out.write("  height:20px;\r\n");
      out.write("  width:35%;\r\n");
      out.write("} \r\n");
      out.write("</style>\r\n");
      out.write("<title>Welcome</title>\r\n");
      out.write("  	\r\n");
      out.write("    <script src=\"/js/vendor/jquery.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery.ebcaptcha.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div style=\"position:absolute; top:0px;\">\r\n");
      out.write("					");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					");
      if (_jspx_meth_s_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr style=\"border-color:  #b9b9b9\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("	<div class=\"twelve column\">\r\n");
      out.write("		\r\n");
      out.write("		<table style=\"width: 100%;\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width=\"25%\" valign=\"top\">\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "activities.jsp", out, false);
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</td>\r\n");
      out.write("<!--<TD> <span> Text <BR><BR> Longer text that stretches out above text-background color... \r\n");
      out.write(" </span></TD> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				--><td width=\"75%\" valign=\"top\">\r\n");
      out.write("					\r\n");
      out.write("					   \r\n");
      out.write("					   <div class=\"customHeader\">\r\n");
      out.write("					   		<i class=\"step fi-list-bullet size-40 \"></i>\r\n");
      out.write("					   		Steps for Online SID Application  \r\n");
      out.write("					   	</div>\r\n");
      out.write("						<br/>\r\n");
      out.write("						<div>\r\n");
      out.write("\r\n");
      out.write("						 <div id=\"table-wrapper\">\r\n");
      out.write("  <div id=\"table-scroll\">\r\n");
      out.write("						<table>\r\n");
      out.write("				                        <tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 1</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Before proceeding you must read the  ");
      if (_jspx_meth_s_005fa_005f0(_jspx_page_context))
        return;
      out.write(" and collect the ");
      if (_jspx_meth_s_005fa_005f1(_jspx_page_context))
        return;
      out.write(".\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 2</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Login to the SID portal with your INDOS number and the password.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 3</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Click on the Link \"Apply for SID\" \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 4</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Check the personal details in the form and click to continue.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 5</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Fill the address details and click continue \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 6</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Fill other details and click continue\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 7</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Make payment through e-payment portal \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 8</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Submit the application \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step 9</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Click on \"Schedule Appointment\" on the screen to schedule an appointment.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step10</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Select the collection centre along with the date and time from the slots available. \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste11\">\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step11</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Your application would be transmitted online to the verification officer, who will check the application.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("                                                        <tr id=\"ste12\">\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step12</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Within 10 days of submission of application, you will receive a notification on the verification result of the application through an e-mail and SMS.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste13\">\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step13</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>You are informed that the fee once paid is non-refundable. Your appointment would be treated as confirmed, only on payment of the fee.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("<tr id=\"ste14\">\r\n");
      out.write("							<td>\r\n");
      out.write("<span>Step14</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>If you wish to reschedule your confirmed appointment (after payment of fee), same can be done do so for maximum two more occasions (excluding the first appointment). If you reschedule your appointment for more than two occasions, then you will have to pay the fee again. In other words fee once paid is valid only for three appointments.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste15\">\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step15</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Please report to the collection centre at the appointed date and time.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste16\">\r\n");
      out.write("							<td>\r\n");
      out.write("								<span>Step16</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Please bring the printout of the Print report/Acknowledgment report,original passport,original CDC and the copy receipt of payent for verification.Data capturing personanel,after examining your dcuments would return the same and caputre your biometric data i.e photograph.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste17\">\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step17</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Seafarers Identity Document would be issued and printed. \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste18\">\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>Step18</span>\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Same shall be dispatched by speed post AD within two working days. \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("<tr id=\"ste19\">\r\n");
      out.write("<td colspan=2>\r\n");
      out.write("<span>Appellate mechanism</span>\r\n");
      out.write("<br> <br> \r\n");
      out.write("The appellate mechanism in case, the candidate is denied an SID-- The appellate mechanism would be offline. First appellate authority would be the Principal Officer. The candidate may approach the Principal Officer having jurisdiction over the shipping master. The Principal Officer, shall, after giving an opportunity y to the candidate of being heard, may pass an order within 15 days of the appeal. \r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr id=\"ste20\">\r\n");
      out.write("<td colspan=2>\r\n");
      out.write("In case, the Candidate is not satisfied with the order of the Principal Officer, he may file a second appeal with the Director General of Shipping, who after giving an opportunity to the candidate, may pass an order within thirty days of such appeal.\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("							</table></div></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" 	\r\n");
      out.write("     <script src=\"/js/foundation.min.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("      	$(document).foundation();\r\n");
      out.write("    </script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("   $(window).load(function() {\r\n");
      out.write("       $(\"#featured\").orbit();\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f0_reused = false;
    try {
      _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f0.setParent(null);
      // /WEB-INF/Welcome2.jsp(50,5) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f0.setTest("%{#session.ERROR_MESSAGE!=null}");
      int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f0);
        }
        do {
          out.write("\r\n");
          out.write("						<div data-alert class=\"alert-box warning radius\" >\r\n");
          out.write("							");
          if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							 <a href=\"#\" class=\"close\">&times;</a>\r\n");
          out.write("						</div>\r\n");
          out.write("						");
          if (_jspx_meth_s_005fset_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      _jspx_th_s_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f0_reused = false;
    try {
      _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      // /WEB-INF/Welcome2.jsp(52,7) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f0.setValue("#session.ERROR_MESSAGE");
      int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
      if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      _jspx_th_s_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:set
    org.apache.struts2.views.jsp.SetTag _jspx_th_s_005fset_005f0 = (org.apache.struts2.views.jsp.SetTag) _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.get(org.apache.struts2.views.jsp.SetTag.class);
    boolean _jspx_th_s_005fset_005f0_reused = false;
    try {
      _jspx_th_s_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      // /WEB-INF/Welcome2.jsp(55,6) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f0.setValue("session.ERROR_MESSAGE");
      // /WEB-INF/Welcome2.jsp(55,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f0.setScope("session");
      // /WEB-INF/Welcome2.jsp(55,6) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f0.setVar("ERROR_MESSAGE");
      int _jspx_eval_s_005fset_005f0 = _jspx_th_s_005fset_005f0.doStartTag();
      if (_jspx_eval_s_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fset_005f0);
        }
        do {
          out.write(' ');
          int evalDoAfterBody = _jspx_th_s_005fset_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.reuse(_jspx_th_s_005fset_005f0);
      _jspx_th_s_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f1 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f1_reused = false;
    try {
      _jspx_th_s_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f1.setParent(null);
      // /WEB-INF/Welcome2.jsp(58,5) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f1.setTest("%{#session.SUCCESS_MESSAGE!=null}");
      int _jspx_eval_s_005fif_005f1 = _jspx_th_s_005fif_005f1.doStartTag();
      if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f1);
        }
        do {
          out.write("\r\n");
          out.write("						<div  data-alert class=\"alert-box warning radius\" style=\"color: black !important;\">\r\n");
          out.write("							");
          if (_jspx_meth_s_005fproperty_005f1(_jspx_th_s_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							 <a href=\"#\" class=\"close\">&times;</a>\r\n");
          out.write("						</div>\r\n");
          out.write("						");
          if (_jspx_meth_s_005fset_005f1(_jspx_th_s_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_s_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f1);
      _jspx_th_s_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f1_reused = false;
    try {
      _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f1);
      // /WEB-INF/Welcome2.jsp(60,7) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f1.setValue("#session.SUCCESS_MESSAGE");
      int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
      if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      _jspx_th_s_005fproperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:set
    org.apache.struts2.views.jsp.SetTag _jspx_th_s_005fset_005f1 = (org.apache.struts2.views.jsp.SetTag) _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.get(org.apache.struts2.views.jsp.SetTag.class);
    boolean _jspx_th_s_005fset_005f1_reused = false;
    try {
      _jspx_th_s_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f1);
      // /WEB-INF/Welcome2.jsp(63,6) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f1.setValue("session.SUCCESS_MESSAGE");
      // /WEB-INF/Welcome2.jsp(63,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f1.setScope("session");
      // /WEB-INF/Welcome2.jsp(63,6) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f1.setVar("SUCCESS_MESSAGE");
      int _jspx_eval_s_005fset_005f1 = _jspx_th_s_005fset_005f1.doStartTag();
      if (_jspx_eval_s_005fset_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fset_005f1);
        }
        do {
          out.write(' ');
          int evalDoAfterBody = _jspx_th_s_005fset_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.reuse(_jspx_th_s_005fset_005f1);
      _jspx_th_s_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fa_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:a
    org.apache.struts2.views.jsp.ui.AnchorTag _jspx_th_s_005fa_005f0 = (org.apache.struts2.views.jsp.ui.AnchorTag) _005fjspx_005ftagPool_005fs_005fa_0026_005faction.get(org.apache.struts2.views.jsp.ui.AnchorTag.class);
    boolean _jspx_th_s_005fa_005f0_reused = false;
    try {
      _jspx_th_s_005fa_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fa_005f0.setParent(null);
      // /WEB-INF/Welcome2.jsp(105,44) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fa_005f0.setAction("InstructionsJSP");
      int _jspx_eval_s_005fa_005f0 = _jspx_th_s_005fa_005f0.doStartTag();
      if (_jspx_eval_s_005fa_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fa_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fa_005f0);
        }
        do {
          out.write("general instructions");
          int evalDoAfterBody = _jspx_th_s_005fa_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fa_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fa_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fa_0026_005faction.reuse(_jspx_th_s_005fa_005f0);
      _jspx_th_s_005fa_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fa_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fa_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fa_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:a
    org.apache.struts2.views.jsp.ui.AnchorTag _jspx_th_s_005fa_005f1 = (org.apache.struts2.views.jsp.ui.AnchorTag) _005fjspx_005ftagPool_005fs_005fa_0026_005faction.get(org.apache.struts2.views.jsp.ui.AnchorTag.class);
    boolean _jspx_th_s_005fa_005f1_reused = false;
    try {
      _jspx_th_s_005fa_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fa_005f1.setParent(null);
      // /WEB-INF/Welcome2.jsp(105,117) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fa_005f1.setAction("ReqdocJSP");
      int _jspx_eval_s_005fa_005f1 = _jspx_th_s_005fa_005f1.doStartTag();
      if (_jspx_eval_s_005fa_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fa_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fa_005f1);
        }
        do {
          out.write("required documents");
          int evalDoAfterBody = _jspx_th_s_005fa_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fa_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fa_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fa_0026_005faction.reuse(_jspx_th_s_005fa_005f1);
      _jspx_th_s_005fa_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fa_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fa_005f1_reused);
    }
    return false;
  }
}
