/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2024-07-21 06:12:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/DUP-REP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ROOT/WEB-INF/lib/struts2-core-2.5.10.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1488779942000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.10.1.jar", Long.valueOf(1721541534948L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fhead_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005factionerror_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005fstyle_005fname_005fmethod_005fid_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005fname_005fmaxlength_005flabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005ftheme_005fmethod_005fkey_005fid_005fclass_005falign_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fhead_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005factionerror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fform_0026_005fstyle_005fname_005fmethod_005fid_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005fname_005fmaxlength_005flabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005ftheme_005fmethod_005fkey_005fid_005fclass_005falign_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fhead_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.release();
    _005fjspx_005ftagPool_005fs_005fform_0026_005fstyle_005fname_005fmethod_005fid_005faction.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005fname_005fmaxlength_005flabel_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005ftheme_005fmethod_005fkey_005fid_005fclass_005falign_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>BSID | Log in </title>\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"/css/foundation.css\" />  	<link rel=\"shortcut icon\" href=\"/images/SID_favicon.png\" type=\"image/x-icon\" />\r\n");
      out.write("  	<link rel=\"shortcut icon\" href=\"/images/SID_favicon.png\" type=\"image/x-icon\" />\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"/css/custom.css\" />\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"/css/foundation-icons/foundation-icons.css\" />\r\n");
      out.write("  	<link href=\"/css/Captchastyle.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("  	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/js/vendor/modernizr.js\"></script>\r\n");
      out.write("    <script src=\"/js/vendor/jquery.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery.ebcaptcha.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .label {\r\n");
      out.write("    	font-size: 20px;\r\n");
      out.write("    	background-color: white;\r\n");
      out.write("    	color: #333333;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    .blink_text {\r\n");
      out.write("\r\n");
      out.write("    animation:1s blinker linear infinite;\r\n");
      out.write("    -webkit-animation:1s blinker linear infinite;\r\n");
      out.write("    -moz-animation:1s blinker linear infinite;\r\n");
      out.write("\r\n");
      out.write("     color: red;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".blink_text_sup {\r\n");
      out.write("animation-name: example;\r\n");
      out.write("    animation:1s example linear infinite;\r\n");
      out.write("    -webkit-animation:1s example linear infinite;\r\n");
      out.write("    -moz-animation:1s example linear infinite;\r\n");
      out.write("\r\n");
      out.write("     color: black;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes example {\r\n");
      out.write("  \r\n");
      out.write("       0%   {color: red;}\r\n");
      out.write("  25%  {color: yellow;}\r\n");
      out.write("  50%  {color: blue;}\r\n");
      out.write("  100% {color: green;}\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("    @-moz-keyframes blinker {  \r\n");
      out.write("     0% { opacity: 0.0; }\r\n");
      out.write("     50% { opacity: 0.5; }\r\n");
      out.write("     100% { opacity: 1.0; }\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("    @-webkit-keyframes blinker {  \r\n");
      out.write("     0% { opacity: 0.0; }\r\n");
      out.write("     50% { opacity: 0.5; }\r\n");
      out.write("     100% { opacity: 1.0; }\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("    @keyframes blinker {  \r\n");
      out.write("     0% { opacity: 0.0; }\r\n");
      out.write("     50% { opacity: 0.5; }\r\n");
      out.write("     100% { opacity: 1.0; }\r\n");
      out.write("     }\r\n");
      out.write(".steps span{\r\n");
      out.write("background-color: #008cba;\r\n");
      out.write("border-color: #007095;\r\n");
      out.write("color: white;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("cursor: default;\r\n");
      out.write("opacity: 0.7;\r\n");
      out.write("box-shadow: none;\r\n");
      out.write("padding: 5px 5px 5px 5px;\r\n");
      out.write(" border: 1px solid  #007095;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write(".myTable td {\r\n");
      out.write("	\r\n");
      out.write("	line-height: 0.9rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label {\r\n");
      out.write("	line-height: 0.9rem !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".myTable input[type=\"text\"], input[type=\"password\"] {\r\n");
      out.write("	\r\n");
      out.write("font-size: 0.875rem;\r\n");
      out.write("margin: 0 0 0.5rem 0;\r\n");
      out.write("padding: 0.5rem;\r\n");
      out.write("height: 2.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("margin: 0 0 0 0;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#table-wrapper {\r\n");
      out.write("  position:relative;\r\n");
      out.write("}\r\n");
      out.write("#table-scroll {\r\n");
      out.write("  height:500px;\r\n");
      out.write("  overflow:auto;  \r\n");
      out.write("  margin-top:20px;\r\n");
      out.write("}\r\n");
      out.write("#table-wrapper table {\r\n");
      out.write("  width:100%;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("#table-wrapper table thead th .text {\r\n");
      out.write("  position:absolute;   \r\n");
      out.write("  top:-20px;\r\n");
      out.write("  z-index:2;\r\n");
      out.write("  height:20px;\r\n");
      out.write("  width:35%;\r\n");
      out.write("} \r\n");
      out.write("</style>\r\n");
      out.write("    \r\n");
      out.write("     ");
      if (_jspx_meth_s_005fhead_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"window.history.forward(1);\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	checkbrowser();\r\n");
      out.write("	$(\"input[type='text']\").bind('copy paste cut',function(e) { \r\n");
      out.write("		e.preventDefault(); //disable cut,copy,paste\r\n");
      out.write("	});\r\n");
      out.write("document.getElementById(\"ste11\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste12\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste13\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste14\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste15\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste16\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste17\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste18\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste19\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste20\").style.display= \"none\";\r\n");
      out.write("/*document.getElementById(\"steH11\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH12\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH13\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH14\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH15\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH16\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH17\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH18\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH19\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH20\").style.display= \"none\";*/\r\n");
      out.write("document.getElementById(\"showlesssteps\").style.display= \"none\";\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	   /* $(function(){\r\n");
      out.write("	       $('#login').ebcaptcha();\r\n");
      out.write("	   }); */\r\n");
      out.write("\r\n");
      out.write("function moresteps()\r\n");
      out.write("{\r\n");
      out.write("document.getElementById(\"showlesssteps\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"showsteps\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste11\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste12\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste13\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste14\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste15\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste16\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste17\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste18\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste19\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste20\").style.display= \"\";\r\n");
      out.write("/*document.getElementById(\"steH11\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH12\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH13\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH14\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH15\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH16\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH17\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH18\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH19\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"steH20\").style.display= \"\";*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function lesssteps()\r\n");
      out.write("{\r\n");
      out.write("document.getElementById(\"showsteps\").style.display= \"\";\r\n");
      out.write("document.getElementById(\"ste11\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste12\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste13\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste14\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste15\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste16\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste17\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste18\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste19\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"ste20\").style.display= \"none\";\r\n");
      out.write("/*document.getElementById(\"steH11\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH12\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH13\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH14\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH15\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH16\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH17\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH18\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH19\").style.display= \"none\";\r\n");
      out.write("document.getElementById(\"steH20\").style.display= \"none\";*/\r\n");
      out.write("document.getElementById(\"showlesssteps\").style.display= \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkbrowser(){\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("	 if (!(navigator.userAgent.indexOf(\"Chrome\") > 0)) {\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("    else\r\n");
      out.write("    	{\r\n");
      out.write("    	alert(\"Please use mozilla firefox browser to login.\");\r\n");
      out.write("		document.getElementById(\"loginBrowserCheck\").style.visibility=\"hidden\";\r\n");
      out.write("		try {\r\n");
      out.write("			document.getElementById(\"loginBrowserCheck\").remove();\r\n");
      out.write("			}\r\n");
      out.write("			catch(err) {\r\n");
      out.write("			  \r\n");
      out.write("			}\r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function formscript()\r\n");
      out.write("{\r\n");
      out.write("	document.getElementById(\"login\").action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/monitorscript\";\r\n");
      out.write("	document.getElementById(\"login\").submit();\r\n");
      out.write("	return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      if (_jspx_meth_s_005factionerror_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<noscript>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("        #loginBrowserCheck {visibility:hidden;}\r\n");
      out.write("    </style>\r\n");
      out.write("    <div class=\"noscriptmsg\" style=\"font-size: 20px;;color: red;padding-left: 12%;padding-top: 1%;padding-bottom: 1%;\">\r\n");
      out.write("    JavaScript is turned off in your web browser. Turn it on to take full advantage of this site, then refresh the page.\r\n");
      out.write("    </div>\r\n");
      out.write("</noscript>\r\n");
      out.write("\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"small12 columns\" style=\"text-align: center;\">\r\n");
      out.write(" <div style=\"position:absolute; top:0px;\">\r\n");
      out.write("					");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					");
      if (_jspx_meth_s_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("</div> \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br/>\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div id=\"notice\" class=\"small-12 columns\" style=\"background-color: lightblue;text-align: center;\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"small-7 columns\" style=\"text-align: center;\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						<div>\r\n");
      out.write("<div id=\"table-wrapper\">\r\n");
      out.write("  <div id=\"table-scroll\">\r\n");
      out.write("						<table class=\"steps myTable\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td colspan=\"2\">\r\n");
      out.write("										<div class=\"customHeader2 \">\r\n");
      out.write("					   						<i class=\"step fi-list-bullet size-40 \"></i>\r\n");
      out.write("					   						Steps for Online SID Application <a href=\"#\" data-reveal-id=\"myModal\"><span style=\"text-align:right !important;color:white !important;border:none;\">(हिंदी)</span></a><br/> \r\n");
      out.write("					   					</div>\r\n");
      out.write("								 </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							1\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td width=\"80%\">\r\n");
      out.write("							Before proceeding you must read the  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Instructions.jsp\">general instructions</a> and collect the <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Reqdoc.jsp\">required documents</a>.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							2\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Login to the SID portal with your INDOS number and the password.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							3\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Click on the Link \"Apply for SID\" \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							4\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Check the personal details in the form and click to continue.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							5\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Fill the address details and click continue \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							6\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Fill other details and click continue\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							7\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Make payment through e-payment portal \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							8\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Submit the application \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							9\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Click on \"Schedule Appointment\" on the screen to schedule an appointment.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							10\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Select the collection centre along with the date and time from the slots available. \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste11\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							11\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Your application would be transmitted online to the verification officer, who will check the application.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("                            <tr id=\"ste12\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							12\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							Within 10 days of submission of application, you will receive a notification on the verification result of the application through an e-mail.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste13\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							13\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>You are informed that the fee once paid is non-refundable. Your appointment would be treated as confirmed, only on payment of the fee.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste14\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							14\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>If you wish to reschedule your confirmed appointment (after payment of fee), same can be done do so for maximum two more occasions (excluding the first appointment). If you reschedule your appointment for more than two occasions, then you will have to pay the fee again. In other words fee once paid is valid only for three appointments.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste15\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							15\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Please report to the collection centre at the appointed date and time.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste16\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							16\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Please bring the printout of the Print report/Acknowledgment report,original passport,original CDC and the copy receipt of payent for verification.Data capturing personanel,after examining your dcuments would return the same and caputre your biometric data i.e photograph.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste17\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							17\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Seafarers Identity Document would be issued and printed. \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste18\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							18\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>Same shall be dispatched by speed post AD within two working days. \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>  \r\n");
      out.write("							<tr id=\"ste19\">\r\n");
      out.write("							<td colspan=2>\r\n");
      out.write("							<span>Appellate mechanism</span>\r\n");
      out.write("							<br> <br>  The appellate mechanism in case, the candidate is denied an SID-- The appellate mechanism would be offline. First appellate authority would be the Principal Officer. The candidate may approach the Principal Officer having jurisdiction over the shipping master. The Principal Officer, shall, after giving an opportunity y to the candidate of being heard, may pass an order within 15 days of the appeal. \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste20\">\r\n");
      out.write("							<td colspan=2>\r\n");
      out.write("							In case, the Candidate is not satisfied with the order of the Principal Officer, he may file a second appeal with the Director General of Shipping, who after giving an opportunity to the candidate, may pass an order within thirty days of such appeal.\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							</table></div></div>\r\n");
      out.write("<input type=\"button\" onClick=\"moresteps()\" value=\"Read More\" id=\"showsteps\">\r\n");
      out.write("<input type=\"button\" onClick=\"lesssteps()\" value=\"Read Less\" id=\"showlesssteps\">\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"myModal\" class=\"reveal-modal\" data-reveal aria-labelledby=\"modalTitle\" aria-hidden=\"true\" role=\"dialog\" style=\"width:60%;left: 60%;background-color: #e0ffff;\">\r\n");
      out.write("  <div id=\"table-wrapper\">\r\n");
      out.write("  <div id=\"table-scroll\">\r\n");
      out.write("						<table class=\"steps myTable\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td colspan=\"2\">\r\n");
      out.write("										<div class=\"customHeader2 \">\r\n");
      out.write("					   						<i class=\"step fi-list-bullet size-40 \"></i>\r\n");
      out.write("					   						ऑनलाइन सीड आवेदन के लिए निम्‍नलिखित चरण<br/> \r\n");
      out.write("					   					</div>\r\n");
      out.write("								 </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							1\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td width=\"80%\">\r\n");
      out.write("							प्रक्रिया  करने से पहले आप सभी <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Reqdoc.jsp\">आवश्‍यक कागजात</a> और <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Instructions.jsp\">सामान्‍य निर्देशों</a> को पढ लें |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							2\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>आपके इनडोस नं.और पासवर्ड से सीड पोर्टल लॉगीन करें |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							3\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							अपलाय फार सीड पर लिंक कर क्लिक करें  |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							4\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							फार्म में वैयक्तिक विवरण जॉच लें और क्लिक करें |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							5\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							संपूर्ण पता भरे और क्लिक करें | \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							6\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							अन्‍य विवरण भी भरे और क्लिक करें |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							7\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							 इ पेमेन्‍ट पोर्टल के माध्‍यम से भूगतान करें |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							8\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							आवेदन प्रस्‍तुत करें |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							9\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							अपाइंटमेन्‍ट शेडयूल पर क्लिक करने पर अपाइंटमेन्‍ट  की शेडयूल स्क्रिन पर दिखाई देगी |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							10\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							 उपलब्‍ध स्‍लाट से कलेक्‍शन सेन्‍टर के साथ दिनांक और समय सिलेक्‍ट करें | \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste11\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							11\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							 आपके आवेदन सत्‍यापित अधिकारी द्वारा जॉच करने पर ऑनलाइन हस्‍तांतरित किए जाएंगे |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("                            <tr id=\"ste12\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							12\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>\r\n");
      out.write("							10 दिन के भीतर आवेदन प्रस्‍तुत करने होगें, आवेदन का सत्‍यापन करने पर इमेल के माध्‍यम से अधिसूचना भेजी जाएगी |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste13\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							13\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>आपको यह सूचित किया जाता है कि शुल्‍क भूगतान होने पर शुल्‍क की वापसी नहीं की जाएगी. आपकी नियुक्ति भूगतान शुल्‍क प्राप्‍त होने पर ही विचारणीय होगी |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste14\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							14\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>(शुल्‍क भूगतान के बाद ही ) अपाइन्‍टमेंट रिशेडयूल विचारणीय होगी,अधिकतम दो और मौकों के लिए ऐसा किया जा सकता है.(पहले अपाइन्‍टमेंट को छोडकर).यदि आप दो से अधिक अवसरों के लिए अपनी नियुक्ति का पुनरीक्षण कर रहे हैं, तब आपको फिर से शुल्‍क का भुगतान करना होगा. दूसरे शब्‍दों में शुल्‍क का भुगतान केवल तीन नियुक्तियों के लिए मान्‍य है |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste15\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							15\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>कृपया नियत दिनांक और समय पर संग्रह केंद्र पर रिपोर्ट करें |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste16\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							16\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>कृपया सत्‍यापन के लिए प्रिंट निकालकर प्रिंट रिपोर्ट/रिपोर्ट पावती,ओरिजनल पासपोर्ट, ओरिजनल सीडीसी और भुगतान की गई रसीद की प्रति साथ लाये. आपके दस्‍तावेजों की जॉच करने के बाद वहीं लौटा दिया जाएगा. कार्मिक अपना डाटा साथ ले जा सकते है और आपके बायोमेट्रिक डाटा ,फोटोग्राफ को साथ ले जा सकते है |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste17\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							17\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>समुद्रकर्मियों का पहचान पत्र जारी और मुद्रित किया जाएगा | \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste18\">\r\n");
      out.write("							<td align=\"right\">\r\n");
      out.write("							18\r\n");
      out.write("							</td>					\r\n");
      out.write("							<td>स्‍पीड पोस्‍ट द्वारा दो दिन में प्रेषित किया जाएगा | \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>  \r\n");
      out.write("							<tr id=\"ste19\">\r\n");
      out.write("							<td></td>\r\n");
      out.write("							<td>\r\n");
      out.write("							<span>अपीलीय तंत्र</span>\r\n");
      out.write("							<br> <br>अपीलीय तंत्र के मामले में, प्रत्‍याशी को सीड से वंचित किया हो - तो अपीलीय तंत्र ऑफलाइन होगी; प्रथम अपीलीय प्राधिकृत मुख्‍य अधिकारी होगें | अभ्‍यर्थी शिंपिग मास्‍टर के अधिकार क्षेत्र वाले मुख्‍य  अधिकारी से संपर्क कर सकते हैं. मुख्‍य अधिकारी द्वारा अभ्‍यर्थी को अवसर प्रदान कर सकते है |  अभ्‍यर्थी द्वारा अपील करने पर 15 दिन के भीतर आदेश जारी किया जा सकता है | \r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr id=\"ste20\">\r\n");
      out.write("							<td></td>\r\n");
      out.write("							<td>\r\n");
      out.write("							एैसे मामले में अभ्‍यर्थी संतुष्‍ट नहीं है तब वह दूसरा अपील नौवहन महानिदेशालय को कर सकता है | एैसे मामले में अभ्‍यर्थी को 30 दिन के भीतर आदेश जारी किया जा सकता है |\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							</table></div></div>\r\n");
      out.write("  <a class=\"close-reveal-modal\" aria-label=\"Close\">&#215;</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"small-5 columns myTable\" style=\"text-align: center;\">\r\n");
      out.write("	\r\n");
      out.write("			");
      if (_jspx_meth_s_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<a href=\"forgotPassword.jsp\" style=\"color: #008CBA;text-align: right;float:right;\">Forgot Password?</a>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"small-12 columns\" style=\"text-align: center;\">\r\n");
      out.write("	 ");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	 <div class=\"bottomStrip\">\r\n");
      out.write("		  © Copyright 2017 DGS\r\n");
      out.write("	<div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\"#notice\").html('<h5><span class=\"blink_text\" style=\"color:red\">Notice :</span><span class=\"blink_text\" ></h5><marquee><h4><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getDocsNews4\" target=\"_new\" style=\"color:green\"><span class=\"blink_text_sup\"><sup>New</sup></span>	BSID Resumed.<span style=\"color:red\"><font size=\"3\">(Read More)</font></span></a></h4></marquee></span>');\r\n");
      out.write("	$(\"#notice\").append(\"<ul><a href=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getDocsNews1\\\" target=\\\"_new\\\" style=\\\"color:green\\\">Safety Instructions....(Read More)</ul>\")\r\n");
      out.write("	$(\"#notice\").append(\"<ul><a href=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getDocsNews2\\\" target=\\\"_new\\\" style=\\\"color:green\\\">Steps for UK Brazil to take appointment....(Read More)</ul>\")\r\n");
      out.write("	$(\"#notice\").append(\"<ul><a href=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getDocsNews3\\\" target=\\\"_new\\\" style=\\\"color:yellow\\\"><span class=\\\"blink_text_sup\\\"></span> Regarding Seafarer Queries : Draft_BSID_Circular (Read More)</ul>\")\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("	/*$(\"#notice\").append(\"<details><summary><span class=\\\"blink_text_sup\\\"><sup>New</sup></span>Seafarers who have appointment date on 14 Jan 2021 in <font color='red'>Vizag only</font>....(Read More)</summary>\"+\r\n");
      out.write("			\"<p>\"+\r\n");
      out.write("			\"Those Seafarers who have taken appointment on 14 Jan 2021 is holiday at Vizag and hence those seafarers who have taken appointment date 14 Jan 2021 have to come to the\"+ \r\n");
      out.write("			\" chosen appointment place Vizag at 15 Jan 2021 or 18 Jan 2021 on working days.\"+\r\n");
      out.write("			\"<br><b>Inconvenience caused in this regards is regretted.</b>\"+\r\n");
      out.write("			\"</p>\"+\r\n");
      out.write("			\"</details>\");*/\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" 	\r\n");
      out.write("     <script src=\"/js/foundation.min.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("      	$(document).foundation();\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:head
    org.apache.struts2.views.jsp.ui.HeadTag _jspx_th_s_005fhead_005f0 = (org.apache.struts2.views.jsp.ui.HeadTag) _005fjspx_005ftagPool_005fs_005fhead_005fnobody.get(org.apache.struts2.views.jsp.ui.HeadTag.class);
    boolean _jspx_th_s_005fhead_005f0_reused = false;
    try {
      _jspx_th_s_005fhead_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fhead_005f0.setParent(null);
      int _jspx_eval_s_005fhead_005f0 = _jspx_th_s_005fhead_005f0.doStartTag();
      if (_jspx_th_s_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fhead_005fnobody.reuse(_jspx_th_s_005fhead_005f0);
      _jspx_th_s_005fhead_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fhead_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fhead_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005factionerror_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:actionerror
    org.apache.struts2.views.jsp.ui.ActionErrorTag _jspx_th_s_005factionerror_005f0 = (org.apache.struts2.views.jsp.ui.ActionErrorTag) _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.get(org.apache.struts2.views.jsp.ui.ActionErrorTag.class);
    boolean _jspx_th_s_005factionerror_005f0_reused = false;
    try {
      _jspx_th_s_005factionerror_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005factionerror_005f0.setParent(null);
      int _jspx_eval_s_005factionerror_005f0 = _jspx_th_s_005factionerror_005f0.doStartTag();
      if (_jspx_th_s_005factionerror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.reuse(_jspx_th_s_005factionerror_005f0);
      _jspx_th_s_005factionerror_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005factionerror_005f0, _jsp_getInstanceManager(), _jspx_th_s_005factionerror_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f0_reused = false;
    try {
      _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f0.setParent(null);
      // /Login.jsp(268,5) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f0.setTest("%{#session.ERROR_MESSAGE!=null}");
      int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f0);
        }
        do {
          out.write("\r\n");
          out.write("						<div data-alert class=\"alert-box warning radius\" >\r\n");
          out.write("							");
          if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							 <a href=\"#\" class=\"close\">&times;</a>\r\n");
          out.write("						</div>\r\n");
          out.write("						");
          if (_jspx_meth_s_005fset_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      _jspx_th_s_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f0_reused = false;
    try {
      _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      // /Login.jsp(270,7) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f0.setValue("#session.ERROR_MESSAGE");
      int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
      if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      _jspx_th_s_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:set
    org.apache.struts2.views.jsp.SetTag _jspx_th_s_005fset_005f0 = (org.apache.struts2.views.jsp.SetTag) _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.get(org.apache.struts2.views.jsp.SetTag.class);
    boolean _jspx_th_s_005fset_005f0_reused = false;
    try {
      _jspx_th_s_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      // /Login.jsp(273,6) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f0.setValue("session.ERROR_MESSAGE");
      // /Login.jsp(273,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f0.setScope("session");
      // /Login.jsp(273,6) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f0.setVar("ERROR_MESSAGE");
      int _jspx_eval_s_005fset_005f0 = _jspx_th_s_005fset_005f0.doStartTag();
      if (_jspx_eval_s_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fset_005f0);
        }
        do {
          out.write(' ');
          int evalDoAfterBody = _jspx_th_s_005fset_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.reuse(_jspx_th_s_005fset_005f0);
      _jspx_th_s_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f1 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f1_reused = false;
    try {
      _jspx_th_s_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f1.setParent(null);
      // /Login.jsp(276,5) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f1.setTest("%{#session.SUCCESS_MESSAGE!=null}");
      int _jspx_eval_s_005fif_005f1 = _jspx_th_s_005fif_005f1.doStartTag();
      if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f1);
        }
        do {
          out.write("\r\n");
          out.write("						<div  data-alert class=\"alert-box info radius\">\r\n");
          out.write("							");
          if (_jspx_meth_s_005fproperty_005f1(_jspx_th_s_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							 <a href=\"#\" class=\"close\">&times;</a>\r\n");
          out.write("						</div>\r\n");
          out.write("						");
          if (_jspx_meth_s_005fset_005f1(_jspx_th_s_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_s_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f1);
      _jspx_th_s_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f1_reused = false;
    try {
      _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f1);
      // /Login.jsp(278,7) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f1.setValue("#session.SUCCESS_MESSAGE");
      int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
      if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      _jspx_th_s_005fproperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:set
    org.apache.struts2.views.jsp.SetTag _jspx_th_s_005fset_005f1 = (org.apache.struts2.views.jsp.SetTag) _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.get(org.apache.struts2.views.jsp.SetTag.class);
    boolean _jspx_th_s_005fset_005f1_reused = false;
    try {
      _jspx_th_s_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f1);
      // /Login.jsp(281,6) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f1.setValue("session.SUCCESS_MESSAGE");
      // /Login.jsp(281,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f1.setScope("session");
      // /Login.jsp(281,6) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fset_005f1.setVar("SUCCESS_MESSAGE");
      int _jspx_eval_s_005fset_005f1 = _jspx_th_s_005fset_005f1.doStartTag();
      if (_jspx_eval_s_005fset_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fset_005f1);
        }
        do {
          out.write(' ');
          int evalDoAfterBody = _jspx_th_s_005fset_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fscope.reuse(_jspx_th_s_005fset_005f1);
      _jspx_th_s_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:form
    org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005fstyle_005fname_005fmethod_005fid_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
    boolean _jspx_th_s_005fform_005f0_reused = false;
    try {
      _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fform_005f0.setParent(null);
      // /Login.jsp(662,3) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setAction("/login.action?typeApp=newApp");
      // /Login.jsp(662,3) name = method type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setMethod("post");
      // /Login.jsp(662,3) name = style type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setCssStyle("text-align:center;  width:100%; margin-top:1.7rem;");
      // /Login.jsp(662,3) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setId("login");
      // /Login.jsp(662,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setName("login");
      int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fform_005f0);
        }
        do {
          out.write("\r\n");
          out.write("			\r\n");
          out.write("			\r\n");
          out.write("			\r\n");
          out.write("			 <tr>\r\n");
          out.write("		    	<td colspan=\"2\">\r\n");
          out.write("		    		<div class=\"customHeader2\">\r\n");
          out.write("						<i class=\"step fi-unlock size-28\"></i>  &nbsp;&nbsp;  \r\n");
          out.write("\r\n");
          out.write("					</div>\r\n");
          out.write("					<div  style=\"text-align: left; color: #333333; line-height: 1rem; font-size: 14px; padding:5px;\">\r\n");
          out.write("					<i class=\"step fi-info size-14\" style=\"color: #008cba;\"></i> use your indos no and indos password to login.\r\n");
          out.write("			\r\n");
          out.write("					</div> 							\r\n");
          out.write("								\r\n");
          out.write("			</td>\r\n");
          out.write("		   </tr>\r\n");
          out.write("		   <tr>\r\n");
          out.write("		    ");
          if (_jspx_meth_s_005ftextfield_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		   ");
          if (_jspx_meth_s_005fpassword_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		  </tr>\r\n");
          out.write("		  <tr>  		    <td align=\"center\" colspan=\"2\">\r\n");
          out.write("		    		    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/Captcha.jpg\" border=\"0\"></td>\r\n");
          out.write("		    		    </tr>\r\n");
          out.write("            ");
          if (_jspx_meth_s_005ftextfield_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		    \r\n");
          out.write("		   <tr>\r\n");
          out.write("		    	<td colspan=\"2\">\r\n");
          out.write("		    		");
          if (_jspx_meth_s_005fsubmit_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		   		\r\n");
          out.write("		   			\r\n");
          out.write("		   		</td>\r\n");
          out.write("		   </tr>\r\n");
          out.write("		  \r\n");
          out.write("		  \r\n");
          out.write("		    \r\n");
          out.write("		  \r\n");
          out.write("		 <tr>\r\n");
          out.write("		 <td>\r\n");
          out.write("		<!-- <input type=\"submit\" id=\"mscr\" name=\"mscr\" style=\"color: transparent; background-color: transparent; border-color: transparent; cursor: default;\" value=\"mscr\">\r\n");
          out.write("		 --></td>\r\n");
          out.write("		 </tr>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fform_0026_005fstyle_005fname_005fmethod_005fid_005faction.reuse(_jspx_th_s_005fform_005f0);
      _jspx_th_s_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f0 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    boolean _jspx_th_s_005ftextfield_005f0_reused = false;
    try {
      _jspx_th_s_005ftextfield_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftextfield_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
      // /Login.jsp(680,6) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextfield_005f0.setName("username");
      // /Login.jsp(680,6) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextfield_005f0.setKey("INDOS NO");
      // /Login.jsp(680,6) name = size type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextfield_005f0.setSize("20");
      // /Login.jsp(680,6) null
      _jspx_th_s_005ftextfield_005f0.setDynamicAttribute(null, "placeholder", "Indos No ");
      // /Login.jsp(680,6) null
      _jspx_th_s_005ftextfield_005f0.setDynamicAttribute(null, "required", "true");
      int _jspx_eval_s_005ftextfield_005f0 = _jspx_th_s_005ftextfield_005f0.doStartTag();
      if (_jspx_th_s_005ftextfield_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
      _jspx_th_s_005ftextfield_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftextfield_005f0, _jsp_getInstanceManager(), _jspx_th_s_005ftextfield_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:password
    org.apache.struts2.views.jsp.ui.PasswordTag _jspx_th_s_005fpassword_005f0 = (org.apache.struts2.views.jsp.ui.PasswordTag) _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody.get(org.apache.struts2.views.jsp.ui.PasswordTag.class);
    boolean _jspx_th_s_005fpassword_005f0_reused = false;
    try {
      _jspx_th_s_005fpassword_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
      // /Login.jsp(681,5) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fpassword_005f0.setName("password");
      // /Login.jsp(681,5) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fpassword_005f0.setKey("PASSWORD");
      // /Login.jsp(681,5) name = size type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fpassword_005f0.setSize("20");
      // /Login.jsp(681,5) null
      _jspx_th_s_005fpassword_005f0.setDynamicAttribute(null, "placeholder", "Indos Password");
      // /Login.jsp(681,5) null
      _jspx_th_s_005fpassword_005f0.setDynamicAttribute(null, "required", "true");
      int _jspx_eval_s_005fpassword_005f0 = _jspx_th_s_005fpassword_005f0.doStartTag();
      if (_jspx_th_s_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fplaceholder_005fname_005fkey_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
      _jspx_th_s_005fpassword_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fpassword_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fpassword_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f1 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005fname_005fmaxlength_005flabel_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    boolean _jspx_th_s_005ftextfield_005f1_reused = false;
    try {
      _jspx_th_s_005ftextfield_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftextfield_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
      // /Login.jsp(686,12) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextfield_005f1.setLabel("Captcha");
      // /Login.jsp(686,12) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextfield_005f1.setName("j_captcha_response");
      // /Login.jsp(686,12) name = size type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextfield_005f1.setSize("20");
      // /Login.jsp(686,12) name = maxlength type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextfield_005f1.setMaxlength("10");
      int _jspx_eval_s_005ftextfield_005f1 = _jspx_th_s_005ftextfield_005f1.doStartTag();
      if (_jspx_th_s_005ftextfield_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005fname_005fmaxlength_005flabel_005fnobody.reuse(_jspx_th_s_005ftextfield_005f1);
      _jspx_th_s_005ftextfield_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftextfield_005f1, _jsp_getInstanceManager(), _jspx_th_s_005ftextfield_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:submit
    org.apache.struts2.views.jsp.ui.SubmitTag _jspx_th_s_005fsubmit_005f0 = (org.apache.struts2.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005ftheme_005fmethod_005fkey_005fid_005fclass_005falign_005fnobody.get(org.apache.struts2.views.jsp.ui.SubmitTag.class);
    boolean _jspx_th_s_005fsubmit_005f0_reused = false;
    try {
      _jspx_th_s_005fsubmit_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
      // /Login.jsp(690,8) name = method type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fsubmit_005f0.setMethod("execute");
      // /Login.jsp(690,8) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fsubmit_005f0.setId("loginBrowserCheck");
      // /Login.jsp(690,8) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fsubmit_005f0.setKey("label.login");
      // /Login.jsp(690,8) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fsubmit_005f0.setValue("Login");
      // /Login.jsp(690,8) null
      _jspx_th_s_005fsubmit_005f0.setDynamicAttribute(null, "align", "center");
      // /Login.jsp(690,8) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fsubmit_005f0.setCssClass("medium button");
      // /Login.jsp(690,8) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fsubmit_005f0.setTheme("simple");
      int _jspx_eval_s_005fsubmit_005f0 = _jspx_th_s_005fsubmit_005f0.doStartTag();
      if (_jspx_th_s_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005ftheme_005fmethod_005fkey_005fid_005fclass_005falign_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
      _jspx_th_s_005fsubmit_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fsubmit_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fsubmit_005f0_reused);
    }
    return false;
  }
}
